name: caviare_flutter_table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 1.0.0
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
